### ISSUE TITLE
WARNING: could not import Base.quit into AtomShell

### ISSUE THREAD

**Issue by gtollefson** [JunoLab/Blink.jl#189]
Hi,

I am running Blink.jl version = "0.10.1" on Julia 1.1 on OS X High Sierra and receive the error  

> WARNING: could not import Base.quit into AtomShell

 when loading the package. It looks like issue #153, was this fixed? 

Thanks,
George

**Comment by pfitzseb** [comment]
Not yet: https://github.com/JunoLab/Blink.jl/issues/142.

**Comment by gtollefson** [comment]
@pfitzseb Any plans to address this soon? This makes the output of our tool a little messy.

**Comment by NHDaly** [comment]
This was fixed on master, in PR #190:
https://github.com/JunoLab/Blink.jl/commit/9fa930a304026f9fca0c48ccae3a2d91214b7601

I think we just haven't cut a release since then.

@pfitzseb I think the biggest change since last release was the WebIO integration in https://github.com/JunoLab/Blink.jl/pull/201. Has that been stable enough that we're happy to tag a release? :) Things seem to have been working for me, though I haven't used Blink much in the last week.

**Comment by pfitzseb** [comment]
Yeah, I think we can tag a release.
